apiVersion: apps/v1
kind: Deployment
metadata:
  name: appplication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: application
  template:
    metadata:
      labels:
        component: application
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: vexl-data
      containers:
        - name: application
          imagePullPolicy: Always
          image: gitlab.cleevio.cz:4567/backend/vexl/vexl-user-ms/staging:latest
          volumeMounts:
            - mountPath: "/var/www/static"
              name: static-files
          env:
            - name: TWILIO_TOKEN
              valueFrom:
                secretKeyRef:
                  key: twilio.token
                  name: spring-profile-user-ms
            - name: TWILIO_PHONE
              valueFrom:
                secretKeyRef:
                  key: twilio.phone
                  name: spring-profile-user-ms
            - name: TWILIO_SID
              valueFrom:
                secretKeyRef:
                  key: twilio.sid
                  name: spring-profile-user-ms